# -*- coding: utf-8 -*-
"""SVM_C.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sfb3CPfZoUC7v-9PC39ufOqZfDhQ-d8c
"""

from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

files.upload()

df = pd.read_csv("credit card taiwan svm algorithm.csv")

df.head(10)

df.isnull().sum()

minAge = df.AGE.mean()
minAge

#Replace all null value in age col
df.AGE = df.AGE.fillna(minAge)

df.head(10)

# separate feature and tergate variable
x = df.drop(["default.payment.next.month"], axis=1)

x

y = df["default.payment.next.month"]
y

# for separate train and test data
from sklearn.model_selection import train_test_split
# svm model
from sklearn.svm import SVC

xTrain , xTest , yTrain , yTest = train_test_split(x , y , test_size=.25, random_state=1)

model = SVC()

model.fit(xTrain , yTrain)

model.predict(xTest)

model.score(xTest , yTest)