# -*- coding: utf-8 -*-
"""NaiveBayesSpamEmail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11NzJ6-dW7YabzhUmJL5HccHPQObLKiGh
"""

from google.colab import files
import pandas as pd

files.upload()

df = pd.read_csv("emails.csv")

df.head()

df.drop_duplicates(inplace = True)

df.shape

# df.drop(df.iloc[:, 2:], axis = 1, inplace = True)
# df.head()

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix , classification_report
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

x = df.text.values
y = df.spam.values

xtrain,xtest,ytrain,ytest = train_test_split(x , y , test_size=0.2)

cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)

x_train.toarray()

model = MultinomialNB()

model.fit(x_train,ytrain)

x_test = cv.transform(xtest)

predict = model.predict(x_test)

model.score(x_test , ytest)

confusion_matrix(ytest , predict)

print(classification_report(ytest , predict))

# spam mail check
spam_mail = ["hy i am looking for a mechine learning tutorial in bangla leanguage", "Hy you win a iphone for free if you go to this link", 
             "You win $1000 in your lucky drew contest got to this link and check"]

spam_mail_test = cv.transform(spam_mail)

model.predict(spam_mail_test)