# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dg68zZWXJ9_396YqRfTl3q92gd4h_H8u
"""

#for file inport
from google.colab import files
files.upload()

#
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# read csv file
df = pd.read_csv("dhaka homeprices.csv")

df.head()

# see data shape
df.shape

# see null value
df.isnull().sum()

# y = mx + c
# x = area (iv)
# y = price(dV)

x = df[['area']]
y = df['price']

#visualization
plt.scatter(df['area'], df['price'])
plt.xlabel("Area")
plt.ylabel("Price")
plt.title("House price in Dhaka")

x

y

#library for divide data set into train and test data
from sklearn.model_selection import train_test_split

#
xTrain, xTest , yTrain , yTest = train_test_split(x , y, test_size=0.30 , random_state=1)

xTrain

xTest

yTrain

yTest

# Import linear reg model from sklearn
from sklearn.linear_model import LinearRegression

reg = LinearRegression()

#train reg model using train data
reg.fit(xTrain , yTrain)

# predect using test data(area)
reg.predict(xTest)

# draw best fit line
plt.scatter(df['area'], df['price'])
plt.xlabel("Area")
plt.ylabel("Price")
plt.title("House price in Dhaka")
plt.plot(df.area , reg.predict(df[['area']]))

# m
m = reg.coef_

#c
c = reg.intercept_

y = m * 5000 + c

y