# -*- coding: utf-8 -*-
"""liReg_pizzaPricePredict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ee1CatJa9J_YhmjEKDpwEFdHkPKxgC05
"""

from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

files.upload()

df = pd.read_csv("pizza_prices.csv" )

df.head

df.shape

df.isnull().sum()

# y = mx + c
# x = area (iv)
# y = price(dV)

x = df[['size']]
y = df['price']

x

y

plt.scatter(df["size"] , df['price'])
plt.xlabel("Pizza Size")
plt.ylabel("Pizza Price")

from sklearn.model_selection import train_test_split

xTrain , xTest , yTrain , yTest = train_test_split(x , y , test_size=0.2, random_state=1)

xTrain

yTrain

from sklearn.linear_model import LinearRegression

reg = LinearRegression()

reg.fit(xTrain , yTrain)

#reg.score(xTrain, yTrain)

reg.predict(xTest)

reg.predict([[17]])

xTest

yTest

plt.scatter(df["size"] , df['price'])
plt.xlabel("Pizza Size")
plt.ylabel("Pizza Price")
plt.plot(df["size"] , reg.predict(df[['size']]))

# m
m = reg.coef_

m

#c
c = reg.intercept_

c

y = m * 17 + c

y